services:
    web-app:
      build:
        context: .
      ports:
        - "8000:8000"
      volumes:
        - ./MirageAgency:/MirageAgency
      environment:
        - DB_HOST=database
        - DB_NAME=dbname
        - DB_USER=dbuser
        - DB_PASS=dbpass

      command: >
        sh -c "
                python3 manage.py migrate &&
                python3 manage.py runserver 0.0.0.0:8000"

      depends_on:
        - database

    database:
      image: postgres:16-alpine
      environment:
        - POSTGRES_DB=dbname
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=dbpass
      ports:
        - 5432:5432

    redis:
      image: redis:7.2.3-alpine
      hostname: redis

    worker:
      build:
        context: .
      hostname: worker
      entrypoint: celery
      command: -A MirageAgency.celery worker --loglevel=info
      volumes:
        - ./MirageAgency:/MirageAgency
      links:
        - redis
      depends_on:
        - redis